%undefine _missing_build_ids_terminate_build
%define __os_install_post %{nil}
%global debug_package %{nil}

# modules defaults
%define modulefile_path_top /usr/local/share/Modules/modulefiles/cudatoolkit

Version:	4.2.9
%define cudamajor %(echo %{version} | cut -d. -f1,2 )
%define cudanumver %(echo %{version} | tr -d .)
Name:		cudatoolkit%{cudanumver}
%define destdir /usr/local/cudatoolkit/%{version}
Release:	6%{?dist}
Summary:	NVIDIA's CUDA Toolkit
Group:		Development/Libraries
License:	NVIDIA
URL:		http://developer.nvidia.com/cuda-toolkit-%(echo %{version}|cut -d. -f1,2| tr -d .)
%if "%{cudamajor}" == "4.0"
Source0:	http://developer.download.nvidia.com/compute/cuda/%(echo %{version}|cut -d. -f1,2| tr . _)/rel/toolkit/cudatoolkit_%{version}_linux_64_rhel6.0.run
Source1:	visualprofiler_4.0.51_linux_64_rhel6.0.tar.gz
# by default goes to /usr/local/cuda/CUDAToolsSDK
Source2:	cudatools_4.0.17_linux_64.run
%else
Source0:	http://developer.download.nvidia.com/compute/cuda/%(echo %{version}|cut -d. -f1,2| tr . _)/rel/toolkit/cudatoolkit_%{version}_linux_64_rhel6.0.run
%endif
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)
ExclusiveArch:	x86_64
Requires:	xorg-x11-drv-nvidia-devel >= 295.41
Requires:	environment-modules
Provides:	cudatoolkit = %{version}
Provides:	cuda = %{version}
AutoReqProv:	0

%description
NVIDIA's CUDA Toolkit

%package doc
Summary:	NVIDIA's CUDA Toolkit Documentation and sample files
Group:		Development/Libraries
Requires:	%{name} = %{version}

%description doc
NVIDIA's CUDA Toolkit Documentation and sample files

%prep
%setup -c -T

%build

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/%{destdir}
pushd $RPM_BUILD_ROOT/%{destdir}
sh %{SOURCE0} --tar xvf
%if "%{cudamajor}" == "4.0"
pushd computeprof/bin
tar xvf %{SOURCE1}
popd
mkdir CUDAToolsSDK
pushd CUDAToolsSDK
sh %{SOURCE2} --tar xvf
popd
%endif
%if "%{cudamajor}" != "4.0"
prefix=%{destdir}
# this is taken from install-linux.pl
cat > bin/nvvp <<ENDNV
#!/bin/sh
LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$prefix/lib:$prefix/lib64 UBUNTU_MENUPROXY=0 LIBOVERLAY_SCROLLBAR=0 $prefix/libnvvp/nvvp
ENDNV
chmod a+x bin/nvvp
%endif
chmod -R a+rX,u+w,og-w .
rm -f install-linux.pl
popd
# we also need it in %{compiler} subdir
mkdir -p $RPM_BUILD_ROOT/%{modulefile_path_top}
cat <<ENDCOREMODULE > ${RPM_BUILD_ROOT}%{modulefile_path_top}/%{version}
#%Module

# NOTE: This is an automatically-generated file!  (generated by the
# %{name} rpm).  Any changes made here will be lost a) if the RPM is
# uninstalled, or b) if the RPM is upgraded or uninstalled.

proc ModulesHelp { } {
   puts stderr "This module adds %{name} %{version} to various paths"
}

module-whatis   "Sets up %{name} %{version} in your environment"

prepend-path PATH "%{destdir}/bin"
prepend-path LD_LIBRARY_PATH "%{destdir}/%{_lib}:%{_libdir}/nvidia"
prepend-path LIBRARY_PATH "%{destdir}/%{_lib}:%{_libdir}/nvidia"
append-path -d { } LDFLAGS "-L%{destdir}/%{_lib} -L%{_libdir}/nvidia"
append-path -d { } INCLUDE "-I%{destdir}/include"
append-path CPATH "%{destdir}/include"
append-path -d { } FFLAGS "-I%{destdir}/include"
append-path -d { } LOCAL_LDFLAGS "-L%{destdir}/%{_lib} -L%{_libdir}/nvidia"
append-path -d { } LOCAL_INCLUDE "-I%{destdir}/include"
append-path -d { } LOCAL_CFLAGS "-I%{destdir}/include"
append-path -d { } LOCAL_FFLAGS "-I%{destdir}/include"
append-path -d { } LOCAL_CXXFLAGS "-I%{destdir}/include"
ENDCOREMODULE

%post
/usr/sbin/alternatives --install /usr/local/cuda cudatoolkit %{destdir} %{cudanumver}

%preun
if [ "$1" = 0 ]; then
    /usr/sbin/alternatives --remove cudatoolkit %{destdir}
fi


%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{destdir}/bin
%{destdir}/include
%{destdir}/lib
%{destdir}/lib64
%{destdir}/open64
%{destdir}/src
%if "%{cudamajor}" == "4.0"
%{destdir}/computeprof
%{destdir}/CUDAToolsSDK
%else
%dir %{destdir}/tools
%{destdir}/extras
%{destdir}/libnvvp
%{destdir}/nvvm
%endif
%dir %{modulefile_path_top}
%{modulefile_path_top}/*

%files doc
%defattr(-,root,root,-)
%doc %{destdir}/doc
%doc %{destdir}/src
%if "%{cudamajor}" != "4.0"
%doc %{destdir}/tools/*xls
%endif

%changelog
* Mon Mar 12 2012 Josko Plazonic <plazonic@math.princeton.edu>
- add support for cuda 4.0

* Fri Mar 09 2012 Josko Plazonic <plazonic@math.princeton.edu>
- move to a different different directory

* Thu Mar 08 2012 Josko Plazonic <plazonic@math.princeton.edu>
- add startup script to setup /dev/nvidia* devices

* Wed Mar 07 2012 Josko Plazonic <plazonic@math.princeton.edu>
- initial build
