%global ruby_sitelib %(ruby -rrbconfig -e "puts Config::CONFIG['sitelibdir']")
%global gemdir %(ruby -rubygems -e 'puts Gem::dir' 2>/dev/null)
%global gemname test-spec
%global geminstdir %{gemdir}/gems/%{gemname}-%{version}

Summary:        Behaviour Driven Development interface for Test::Unit
Name:           rubygem-%{gemname}
Version:        0.10.0
Release:        2%{?dist}
Group:          Development/Languages
License:        Ruby or GPLv2
URL:            http://test-spec.rubyforge.org
Source0:        http://gems.rubyforge.org/gems/%{gemname}-%{version}.gem
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:       ruby(abi) = 1.8
Requires:       rubygems
BuildRequires:  rubygems
BuildArch:      noarch
Provides:       rubygem(%{gemname}) = %{version}

%description
Test/spec layers an RSpec-inspired interface on top of Test::Unit, so you
can mix TDD and BDD (Behavior-Driven Development).  It is a clean-room
implementation that maps most kinds of Test::Unit assertions to a
should-like syntax.


%prep


%build


%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{gemdir}
gem install --local --install-dir $RPM_BUILD_ROOT%{gemdir} \
            --force --rdoc %{SOURCE0}
mkdir -p $RPM_BUILD_ROOT/%{_bindir}
mv $RPM_BUILD_ROOT%{gemdir}/bin/* $RPM_BUILD_ROOT/%{_bindir}
rmdir $RPM_BUILD_ROOT%{gemdir}/bin
find $RPM_BUILD_ROOT%{geminstdir}/bin -type f |xargs chmod a+x


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-, root, root, -)
%{_bindir}/specrb
%dir %{geminstdir}
%dir %{geminstdir}/bin
%attr(0755,root,root) %{geminstdir}/bin/specrb
%{geminstdir}/lib
%{geminstdir}/Rakefile
%doc %{geminstdir}/examples
%doc %{geminstdir}/test
%doc %{geminstdir}/README
%doc %{geminstdir}/SPECS
%doc %{geminstdir}/ROADMAP
%doc %{geminstdir}/TODO
%doc %{gemdir}/doc/%{gemname}-%{version}
%{gemdir}/cache/%{gemname}-%{version}.gem
%{gemdir}/specifications/%{gemname}-%{version}.gemspec


%changelog
* Wed Jul 08 2009 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> - 0.10.0-2
- Fix up license
- Consistent use of macros
- Dependency on Ruby ABI

* Thu Jun 25 2009 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> - 0.10.0-1
- Package generated by gem2rpm
- Fix up plist
