%global gemdir %(ruby -rubygems -e 'puts Gem::dir' 2>/dev/null)
%global gemname bacon
%global geminstdir %{gemdir}/gems/%{gemname}-%{version}

Summary:        A ruby-based testing framework
Name:           rubygem-%{gemname}
Version:        1.1.0
Release:        3%{?dist}
Group:          Development/Languages
License:        MIT
URL:            http://chneukirchen.org/repos/bacon
Source0:        http://gems.rubyforge.org/gems/%{gemname}-%{version}.gem
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:       rubygems
Requires:       ruby(abi) = 1.8
BuildRequires:  rubygems
BuildRequires:  rubygem(rake)
BuildArch:      noarch
Provides:       rubygem(%{gemname}) = %{version}

%description
Bacon is a small and lightweigt RSpec clone, providing essential
spec framework features.


%prep


%build


%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{gemdir}
gem install --local --install-dir $RPM_BUILD_ROOT%{gemdir} \
            --force --rdoc %{SOURCE0}
mkdir -p $RPM_BUILD_ROOT/%{_bindir}
mv $RPM_BUILD_ROOT%{gemdir}/bin/* $RPM_BUILD_ROOT/%{_bindir}
rmdir $RPM_BUILD_ROOT%{gemdir}/bin
find $RPM_BUILD_ROOT%{geminstdir}/bin -type f |xargs chmod a+x

# Derop weird non-utf8 characters in e-mail framework
LANG=C sed 's/\xc2//g' -i $RPM_BUILD_ROOT%{geminstdir}/ChangeLog


%check
cd $RPM_BUILD_ROOT%{geminstdir}
rake test --trace


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-, root, root, -)
%{_bindir}/bacon
%dir %{geminstdir}
%dir %{geminstdir}/bin
%attr(0755,root,root) %{geminstdir}/bin/bacon
%{geminstdir}/lib
%{geminstdir}/Rakefile
%doc %{geminstdir}/test
%doc %{geminstdir}/README
%doc %{geminstdir}/RDOX
%doc %{geminstdir}/COPYING
%doc %{geminstdir}/ChangeLog
%doc %{gemdir}/doc/%{gemname}-%{version}
%{gemdir}/cache/%{gemname}-%{version}.gem
%{gemdir}/specifications/%{gemname}-%{version}.gemspec


%changelog
* Sun Jul 26 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.1.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_12_Mass_Rebuild

* Mon Jun 29 2009 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> - 1.1.0-2
- Run tests
- Drop useless macro

* Thu Jun 25 2009 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> - 1.1.0-1
- Package generated by gem2rpm
- Fix up plist
- Make rpmlint happy
